### ISSUE TITLE
Compiling Anura3D Problem

### ISSUE THREAD

**Issue by Geotechnique-simlation** [Anura3D/Anura3D_OpenSource#9]
2019VS
2022One API

warning #8889: Explicit interface or EXTERNAL declaration is required.   [GIVEERROR]

**Comment by murphy-john** [comment]
Hi @Geotechnique-simlation, will you ask this question again in the discussions tab? There is an active discussion topic about  compiling issues.  There might already be an answer there.

Also, when you ask the question again, will you provide more detail about your issue? At what point did the issue occur?
